### ISSUE TITLE
Need some additional info on DumpFlash, please

### ISSUE THREAD

**Issue by p1ngb4ck** [ohjeongwook/DumpFlash#1]
Dear Sir,
first of all, I want to thank you so much for your work. I appreciate it SO much, since this is exactly what I was looking for, when wondering, how I could possibly change the NAND-flash of an STB I`d like to repair. (Was looking for a way on how to write the CFE for a Broadcom-STB to the new flash chip).
Since I had been successfully using my TUMPA Lite to write CFEs to I2C/SPI eeproms, I was already familiar with ft2232h in general, and I was extremely glad when I found your project.
So, I ordered 2 of those YAMAICHI TSOP48-ZIF Sockets, a new FT2232H breakout board (since my TUMPA Lite had only 1 Channel UART channel available, using the FT2232HL chip) and two TSOP48-DIP adapters, for direct soldering.
I installed pyusb. pyserial and pyftdi (from https://github.com/eblot/pyftdi ) and tried to use DumpFlash, but I was not able to get any answer from one of the four NAND chips I desoldered from old USB-flash devices. No ID, nothing, although I built two adapters and soldered one of those nands to one of that adapterboards. I am struggling on this for two weeks now, and I am pretty sure my wiring is correct and I checked the wirings with an ohmmeter directly from ft2232h-pins to the pins of the flash.
Theoretically it could be I damaged the flash, but I can hardly believe that, since its same issue with 4 flash chips now, and I have been insanely careful (didnt have to keep those old original usb-flash stick boards alive, so I just cared for the chip) 
Could you please help me out with some info on the following ? :
- Which NAND-chips _should_ work ? only "pure" normal SLC NAND or SLC DDP or even MLC also?
- Which pyftdi version do you use?
- On the spritesmod sheet, the pin-description of the FT2232H that goes to GND is hardly readable.
  Thanks a lot for your awesome schematics :) But could it be that this pin is BCBUS 4 instead of 6 you used in your schematics? .. Probably not, sry. Just wondering because that Number is so hard to identify on the original spritesmods sheet, and I am wondering that I wasn`t able to get any response during last two weeks, after checking everything about a hundred times.

The device I use is the one available here : http://www.elv.de/elv-highspeed-mini-usb-modul-um-ft2232h-komplettbausatz.html (german page sry). It just gives me direct access to all AC/AD and BC/BD Bus lines, as well as 3.3V and 5V pinouts. Those Rx/Tx LEDs on the picture are connected to ACBus 3 + 4 and BCBus 3 + 4, so I guess those should not interfere, but I took them out as well, with no change.
It is enumerating as default ft2232h (0403/6010), and I have tested the board itself using I2C/SPI and JTAG connections already (so I suppose the board is not done).

If you have any idea what I may be doing wrong, I would be too glad xD
Thanks a lot in advance,
Oliver

**Comment by ohjeongwook** [comment]
I remember mostly those issues are related to grounding... Can you try to
pull off GND line during you try to dump the flash? What can you observe?

On Fri, Feb 13, 2015 at 3:00 AM, Oliver Kleinecke notifications@github.com
wrote:

> Dear Sir,
> first of all, I want to thank you so much for your work. I appreciate it
> SO much, since this is exactly what I was looking for, when wondering, how
> I could possibly change the NAND-flash of an STB I`d like to repair. (Was
> looking for a way on how to write the CFE for a Broadcom-STB to the new
> flash chip).
> Since I had been successfully using my TUMPA Lite to write CFEs to I2C/SPI
> eeproms, I was already familiar with ft2232h in general, and I was
> extremely glad when I found your project.
> So, I ordered 2 of those YAMAICHI TSOP48-ZIF Sockets, a new FT2232H
> breakout board (since my TUMPA Lite had only 1 Channel UART channel
> available, using the FT2232HL chip) and two TSOP48-DIP adapters, for direct
> soldering.
> I installed pyusb. pyserial and pyftdi (from
> https://github.com/eblot/pyftdi ) and tried to use DumpFlash, but I was
> not able to get any answer from one of the four NAND chips I desoldered
> from old USB-flash devices. No ID, nothing, although I built two adapters
> and soldered one of those nands to one of that adapterboards. I am
> struggling on this for two weeks now, and I am pretty sure my wiring is
> correct and I checked the wirings with an ohmmeter directly from
> ft2232h-pins to the pins of the flash.
> Theoretically it could be I damaged the flash, but I can hardly believe
> that, since its same issue with 4 flash chips now, and I have been insanely
> careful (didnt have to keep those old original usb-flash stick boards
> alive, so I just cared for the chip)
> Could you please help me out with some info on the following ? :
> - Which NAND-chips _should_ work ? only "pure" normal SLC NAND or SLC
>   DDP or even MLC also?
> - Which pyftdi version do you use?
> - On the spritesmod sheet, the pin-description of the FT2232H that
>   goes to GND is hardly readable. Thanks a lot for your awesome schematics :)
>   But could it be that this pin is BCBUS 4 instead of 6 you used in your
>   schematics? .. Probably not, sry. Just wondering because that Number is so
>   hard to identify on the original spritesmods sheet, and I am wondering that
>   I wasn`t able to get any response during last two weeks, after checking
>   everything about a hundred times.
> 
> The device I use is the one available here :
> http://www.elv.de/elv-highspeed-mini-usb-modul-um-ft2232h-komplettbausatz.html
> (german page sry). It just gives me direct access to all AC/AD and BC/BD
> Bus lines, as well as 3.3V and 5V pinouts. Those Rx/Tx LEDs on the picture
> are connected to ACBus 3 + 4 and BCBus 3 + 4, so I guess those should
> interfere, but I took them out as well, with no change.
> It is enumerating as default ft2232h (0403/6010), and I have tested the
> board itself using I2C/SPI and JTAG connections already (so I suppose the
> board is not done).
> 
> If you have any idea what I may be doing wrong, I would be too glad xD
> Thanks a lot in advance,
> Oliver
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohjeongwook/DumpFlash/issues/1.

## 

-matt
Visit http://darungrim.org for free and opensource binary diffing tool.

**Comment by p1ngb4ck** [comment]
WOW!!! This is something that should definitely be added as a tip to the project-sheet. After 2 weeks of searching, it helped pulling of GND :+1 
I was now able to use NandTool correctly =))))) (DumpFlash breaks (with timeout) after exactly 27 or 30 blocks, but NandTool works like a charm now !!) I love you man :) A working VU+ Ultimo is getting closer :)

**Comment by ohjeongwook** [comment]
:)

I just want to know why DumpFlash stuck later... but you might help
debugging that later when you have some free time, I guess.

Have a good day!

On Fri, Feb 13, 2015 at 12:59 PM, Oliver Kleinecke <notifications@github.com

> wrote:
> 
> WOW!!! This is something that should definitely be added as a tip to the
> project-sheet. After 2 weeks of searching, it helped pulling of GND :+1
> I was now able to use NandTool correctly =))))) (DumpFlash breaks (with
> timeout) after exactly 27 or 30 blocks, but NandTool works like a charm now
> !!) I love you man :) A working VU+ Ultimo is getting closer :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohjeongwook/DumpFlash/issues/1#issuecomment-74325856.

## 

-matt
Visit http://darungrim.org for free and opensource binary diffing tool.

**Comment by p1ngb4ck** [comment]
Thanks a lot.. day is almost over here in germany.. but I stay up late working anyways. I would be glad to help you debugging. Just tell me how I could possibly pass you relating info, and I will try to provide as soon as I am home again

**Comment by ohjeongwook** [comment]
1. Maybe just some exception info will be helpful.
2. Also breakout board model and exact NAND flash model no.?
3. What command line option did you use?

Thanks.

On Fri, Feb 13, 2015 at 1:28 PM, Oliver Kleinecke notifications@github.com
wrote:

> Thanks a lot.. day is almost over here in germany.. but I stay up late
> working anyways. I would be glad to help you debugging. Just tell me how I
> could possibly pass you relating info, and I will try to provide as soon as
> I am home again
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohjeongwook/DumpFlash/issues/1#issuecomment-74329975.

## 

-matt
Visit http://darungrim.org for free and opensource binary diffing tool.

**Comment by p1ngb4ck** [comment]
Hi !
I put everything together to a wgetpaste, you can see here : https://bpaste.net/show/6e13cfbf04b8

Hope this may help. As far as I can see, it does get some correct flash information when invoking "DumpFlash -i" without -S option, and some info is wrong. What I find kind of interesting, is that it does get exactly those information with the -S option.. but in slow mode, it doesn`t get the other info correctly any more.

**Comment by p1ngb4ck** [comment]
Oh, I forgot .. the breakout board is UM-FT2232H. Link to vendor with picture above.

**Comment by p1ngb4ck** [comment]
OK, I think that issue here may be closed.
The issue is (mostly) dedicated to wrong chip identification. The identification of Pagesize based on ID doesn`t work, thats why DumpFlash couldn`t work.
Reading works now, I am afraid Block-Erase and write doesn`t ... yet
I hope it is okay for you if I reuse most of your functions for my own tool. Want to have a NAND-tool that is capable of binary reading/writing/erasing. Most people will surely prefer yours, if the topic is about reverse engineering or data rescue. In my case I just want to achieve to (re-)write valid known CFE code to a specific offset and validate it.
I therefore have no real use for all those JFFS2 and UBoot detection and correction stuff.
Also : I will definitely base my own tool on python json/xml descriptor files ---
there is just too much that can go wrong with autodetection. People who want do access NANDs with a tool like this SHOULD get out the datasheet themselves and write their own descriptor.
Oh .. and 12Hz mode MUST have a timing problem. Didn`t find the reason yet.

**Comment by ohjeongwook** [comment]
Thanks for the elaboration. I still want to know what is exactly happening here. The chip identification code is from NAND tool and it is originally from Linux kernel module code. So, I don't think it will be totally wrong? Probably some logic error when DumpFlash is using the information?

**Comment by p1ngb4ck** [comment]
OK, so jfyi as additional information : 
One of the NANDs I tested with the most, is the Samsung NAND in the bpaste I linked.
when I added correct pagesize and BlockSize manually to FlashDevice.py, reading in 60Hz worked. reading with -S (slow option) returns bad info from the chip (I get the ec for manufaturer ID returned as Chip ID which is D3) and reading stops after few pages with timeout (which is obviously related to getting wrong chip info). The difference between those can be seen in the bpaste also right at the start.
I am though not yet able (neither with NandTool nor DumpFlash) to write and revalidate or to erase (and validate erase).
PS : In FlashDevice.py, in lines 298 + 299 : is this correct? shouldnt be the raw block be the bigger one with oob data? or is this just mixed up?

**Comment by learntofly83** [comment]
I am not a programmer although as a long time computer power user I can follow most languages at a basic level. I too notices what appeared to be an issue with the rawblock caculation

**Comment by p1ngb4ck** [comment]
I managed to locate the basic source of the problem. the address calculation for LP-Nands is not correct. have a "working" project, i will release soon.

**Comment by j706326** [comment]
@p1ngb4ck @ohjeongwook 

Hi, I also do have the same ftdi board like p1ngb4ck and unfortunately the same issue that I get no ID, nothing, not even the USB getting recognized once the NAND is in the socket.
Could you explain what you mean by pull of the ground line?
Or if @p1ngb4ck could explain what he did to the board to get it recognized with the NAND?

Best Regards,
j706326
