### ISSUE TITLE
XOR issue?

### ISSUE THREAD

**Issue by DataDrug** [ohjeongwook/DumpFlash#11]
I've been looking into this project on and off for some time, but I never could completly understand this fully.

When I dump a NAND, i grab the image and i try to carve it with data recovery tools like r-studio.
The only time I had sucess was with some old mp3 player, but even there, the songs were corrupted, but I could see MFT correctly, file names and even hear some bits of the songs.

I believe this is related to XOR, am I right?
Thanks!

**Comment by ohjeongwook** [comment]
Some usb devices might use internal encoding mechanism. In that case, you need to figure out the algorithm to decode them. But, most of the NAND flash from embedded devices will look OK. 

Another problem might be related to OOB. For every pages of the raw image, NAND flash will insert OOB checksum bytes. You need to remove them to make the pages make sense as stream of data.
