### ISSUE TITLE
Syntax Error `jffs 2=`

### ISSUE THREAD

**Issue by wiperpaul** [ohjeongwook/DumpFlash#18]
`jffs 2=` here is causing a syntax error is it supposed to be `jffs2=` ?

https://github.com/ohjeongwook/DumpFlash/blob/c5c16dd2087faae8147fe136e97e3813dff106ca/FlashUtil.py#L284

**Comment by ohjeongwook** [comment]
https://github.com/ohjeongwook/DumpFlash/commit/c2f3f332f27962065ac3bc3f67635c6b50aaa8e3
