### ISSUE TITLE
nandRead function wrong in slow-mode

### ISSUE THREAD

**Issue by p1ngb4ck** [ohjeongwook/DumpFlash#2]
Hi !
Just as a small feedback:
I found the reason for a part of the errors I experience with DumpFlash:
the nandRead function doesn`t return every second byte in slow-mode only (please compare bkerler`s code for nand-read in slow-mode : he explicitly states, that in slow-mode, ftdi-read function returns every byte twice ("doubled"). The read function therefore has to compensate for that, which it currently doesn`t in FlashDevice.py.
While writing my own pure C code, I also could verify this behaviour (doubled bytes return in slow-mode)
I didn`t find the reason for the erroneous Flash-Detection (works correct in NandTool) yet. But thats whats next in my own code, so I`m sure I will find it soon.. (when tinkering around with my own code).
Best regards,
Oliver

**Comment by p1ngb4ck** [comment]
Also : Despite to bkerlers code, the device-initialization works correctly in DumpFlash, which helped me a lot to debug the initialization in C / build my own code. thanks a lot again

**Comment by ohjeongwook** [comment]
Good info. I didn't see that behavior personally. I'll test myself if I can repro this.

**Comment by ohjeongwook** [comment]
Couldn't repro. Closing the issue.
