### ISSUE TITLE
'bytearray' object has no attribute 'tobytes'

### ISSUE THREAD

**Issue by MagicTechs** [ohjeongwook/DumpFlash#20]
hi,
I have a problem to compile the code.

AttributeError: 'bytearray' object has no attribute 'tobytes'
Maybe someone know why this bug happen and how to solve them?

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

root@ja-H81M-HD3:/home/ja/Desktop/dumpflash-master/dumpflash# pip3 install git+https://github.com/ohjeongwook/dumpflash --upgrade
Collecting git+https://github.com/ohjeongwook/dumpflash
  Cloning https://github.com/ohjeongwook/dumpflash to /tmp/pip-gvhwqu20-build
Collecting pyftdi (from dumpflash-ohjeongwook==0.0.1)
Requirement already up-to-date: pyusb>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from pyftdi->dumpflash-ohjeongwook==0.0.1)
Requirement already up-to-date: pyserial>=3.0 in /usr/local/lib/python3.6/dist-packages (from pyftdi->dumpflash-ohjeongwook==0.0.1)
Installing collected packages: pyftdi, dumpflash-ohjeongwook
  Found existing installation: pyftdi 0.29.6
    Uninstalling pyftdi-0.29.6:
      Successfully uninstalled pyftdi-0.29.6
  Found existing installation: dumpflash-ohjeongwook 0.0.1
    Uninstalling dumpflash-ohjeongwook-0.0.1:
      Successfully uninstalled dumpflash-ohjeongwook-0.0.1
  Running setup.py install for dumpflash-ohjeongwook ... done
Successfully installed dumpflash-ohjeongwook-0.0.1 pyftdi-0.42.2
root@ja-H81M-HD3:/home/ja/Desktop/dumpflash-master/dumpflash# python3 dumpflash.py
Traceback (most recent call last):
  File "dumpflash.py", line 53, in <module>
    flash_image_io = flashimage.IO(options.raw_image_filename, options.start_offset, options.length, options.page_size, options.oob_size, options.pages_per_block, options.slow)
  File "/home/ja/Desktop/dumpflash-master/dumpflash/flashimage.py", line 24, in __init__
    self.SrcImage = flashdevice.IO(slow)
  File "/home/ja/Desktop/dumpflash-master/dumpflash/flashdevice.py", line 56, in __init__
    self.__get_id()
  File "/home/ja/Desktop/dumpflash-master/dumpflash/flashdevice.py", line 157, in __get_id
    flash_identifiers = self.__read_data(8)
  File "/home/ja/Desktop/dumpflash-master/dumpflash/flashdevice.py", line 141, in __read_data
    return self.__read(0, 0, count)
  File "/home/ja/Desktop/dumpflash-master/dumpflash/flashdevice.py", line 100, in __read
    return data.tobytes()
AttributeError: 'bytearray' object has no attribute 'tobytes'

best regards
Patrick

**Comment by ohjeongwook** [comment]
The flashdevice part of the code is not fully tested yet during our port effort from Python 2.7 to 3.x. I'll check this soon to fix it.

**Comment by ohjeongwook** [comment]
Fixed with https://github.com/ohjeongwook/dumpflash/commit/fc0c3e13909c9f08e8a4ad90a5a7e0bc02ae1544
