### ISSUE TITLE
Support for SPI nand flash

### ISSUE THREAD

**Issue by asmitaj08** [ohjeongwook/DumpFlash#21]
Hello, 
Got inspired by this work for Parallel NAND flash, I want to work to create similar for SPI NAND flash. Could you please guide in what way should I proceed? I already have my FT232 based board with it's SPI interface, I wanted guidance in terms of its software development.

Kindly suggest.

Thanks & Regards
Asmita

**Comment by wiperpaul** [comment]
Read the documentation on the main page.
- https://github.com/ohjeongwook/dumpflash/blob/master/README.md#documentations

This code is for the FTDI bit-bang approach to NAND Flash for SPI NAND chips you are limited in your options for a custom programmer. Here is what I found in 5 minutes on google.

- https://github.com/nfd/spi-flash-programmer
- https://github.com/flashrom/flashrom/pull/62

**Comment by asmitaj08** [comment]
Hi,
Thanks for your response. 
The SPI IC I am using is http://pro0fc108.hkpic1.websiteonline.cn/upload/PN26Q01AWSIUG.pdf
It's 128 MB NAND Flash, flashrom only supports NOR flash. Well, I found FTDI library for MPSSE - https://www.ftdichip.com/Support/Documents/AppNotes/AN_178_User%20Guide%20for%20LibMPSSE-SPI.pdf .

I think, I should proceed with this. 

Thanks and Regards
Asmita
