### ISSUE TITLE
Typo in FlashDevice.py ?

### ISSUE THREAD

**Issue by p4r4d0x86** [ohjeongwook/DumpFlash#5]
Hi,

Thanks a lot for the tool :+1: 

Just to say, it seems there is a typo in FlashDevice.py file ?
File "/home/xubuntu/Desktop/DumpFlash/FlashDevice.py", line 1, in <module>
    from pyftdi.pyftdi.ftdi import *

Works better with "pyftdi.ftdi import" ? I am right ?

Kind regards,
Nico

**Comment by ohjeongwook** [comment]
I guess it is the standard usage I saw at the time of writing the code. Doesn't it work for you? Can you let me know which pyftdi did you use?

**Comment by ohjeongwook** [comment]
I realized that pyftdi has been updated and the naming I used doesn't work anymore. I'll push new code soon.

**Comment by Stoobs** [comment]
Any chance of that code push after two years? :)

**Comment by ohjeongwook** [comment]
This should have been fixed with merge: https://github.com/ohjeongwook/DumpFlash/pull/16
